### PR TITLE
Update privacy_wording.json

### PR DESCRIPTION
**Pull request by max-ostapenko**
1. Fixed the JSON structure
2. Couple of more wordings added
3. Changed wordings to lower case, case-insensitive pattern to be used

### CODE REVIEW

**Comment by max-ostapenko** [comment]
@mrtn3000 can we merge it to the master?

**Comment by mrtn3000** [comment]
Due to the format change I can't spot what changes you in #3 can you point them out for me?

**Comment by max-ostapenko** [comment]
I've updated formatting to make it more visible.
Now formatting aligned across all countries.

**Comment by mrtn3000** [comment]
ok thanks. I didn't see any changes in the words itself

**Pull request merged**
